{
  lib,
  pkgs,
  ...
}:
let
  name = "secrets";

  helpText = ''
    ${name} - manage sops-encrypted secrets for this flake

    USAGE: ${name} <command> [args]

    COMMANDS:
      rekey            Regenerate .sops.yaml from pubkeys, then re-encrypt all
                       managed files to match (sops updatekeys)
      check            Assert every encrypted file's recipients match .sops.yaml
                       (read-only; safe for CI; no decryption)
      edit <name>      Create or rotate a raw secret secrets/values/<name>
      render <tpl>     Render a text template to a 0600 tmpfs file, print its path
                       (app-side activation; decrypts refs, raw-substitutes)
      for              List the raw secrets defined in this flake

    OPTIONS:
      -h, --help       Show this help'';
in
{
  type = "app";
  meta = {
    description = "Manage sops-encrypted secrets (rekey, check, edit)";
    license = lib.licenses.mit;
    maintainers = with lib.maintainers; [ codgician ];
  };

  program = lib.getExe (
    pkgs.writeShellApplication {
      inherit name;
      runtimeInputs = with pkgs; [
        coreutils
        git
        nix
        sops
        ssh-to-age
        yq-go
      ];

      text = ''
        set -euo pipefail

        err() { echo "Error: $*" >&2; exit 1; }
        log() { echo "$*" >&2; }

        show_help() { cat >&2 <<'EOF'
        ${helpText}
        EOF
        }

        repo_root() { git rev-parse --show-toplevel; }

        # Convert an ssh ed25519 public key to its age recipient.
        ssh_pub_to_age() { ssh-to-age; }

        # Emit .sops.yaml from the flake's sopsRules metadata. Public keys only.
        do_rekey() {
          local root rules
          root="$(repo_root)"
          cd "$root"
          rules="$(nix eval --json '.#sopsRules')"

          {
            echo "# Generated by \`nix run .#${name} -- rekey\`. Do not edit."
            echo "creation_rules:"
            echo "$rules" | yq -r '.[] | @json' | while read -r rule; do
              local path regex anchored
              path="$(echo "$rule" | yq -r '.path')"
              regex="$(echo "$rule" | yq -r '.encryptedRegex // ""')"
              # Anchor and escape so one path matches exactly one rule. Without
              # this, a literal '.' in a path is a regex wildcard and a shorter
              # path could prefix-match a longer rule.
              # shellcheck disable=SC2016  # the sed program is intentionally literal
              anchored="^$(printf '%s' "$path" | sed 's/[.[\*^$()+?{|]/\\&/g')\$"
              echo "  - path_regex: ${"\${anchored}"}"
              [ -z "$regex" ] || echo "    encrypted_regex: '${"\${regex}"}'"
              echo "    key_groups:"
              echo "      - age:"
              echo "$rule" | yq -r '.sshKeys[]' | while read -r sshkey; do
                local age
                age="$(echo "$sshkey" | ssh_pub_to_age)"
                echo "          - ${"\${age}"}"
              done
            done
          } > secrets/.sops.yaml

          git add secrets/.sops.yaml
          log "Wrote secrets/.sops.yaml"

          # Re-encrypt every existing managed file to current recipients.
          shopt -s nullglob
          local files=(secrets/values/*)
          if [ ''${#files[@]} -gt 0 ]; then
            ( cd secrets && sops updatekeys --yes "''${files[@]#secrets/}" )
            git add secrets/values
            log "Re-encrypted ''${#files[@]} managed file(s) to current recipients"
          else
            log "No managed files to re-encrypt yet"
          fi
        }

        # Read a sops file's actual age recipients without decrypting. Every
        # managed file is a binary values/* sops file storing its metadata as
        # JSON, exposing recipients at .sops.age[].recipient.
        file_recipients() {
          yq -p json -r '.sops.age[].recipient' "$1" 2>/dev/null | sort -u
        }

        # The age recipients of the creation_rule whose path_regex matches $1.
        # Emits nothing if no rule matches; the caller distinguishes 0/1/many.
        # NOTE: `.path_regex as $re | strenv(P) | test($re)` binds the rule's
        # regex BEFORE piping the path into test(); evaluating test(.path_regex)
        # in the string context instead matches every rule (silent over-match).
        rule_recipients_for() {
          # shellcheck disable=SC2016  # yq DSL; P is read via strenv(), not shell
          P="$1" yq -r '
            .creation_rules[]
            | select(.path_regex as $re | strenv(P) | test($re))
            | .key_groups[].age[]
          ' .sops.yaml | sort -u
        }

        # Count how many creation_rules match a given path (ambiguity guard).
        rules_matching() {
          # shellcheck disable=SC2016  # yq DSL; P is read via strenv(), not shell
          P="$1" yq -r '
            [ .creation_rules[] | select(.path_regex as $re | strenv(P) | test($re)) ] | length
          ' .sops.yaml
        }

        # Validate the REGISTRY-DERIVED set of managed paths (.#sopsRules), not a
        # filesystem glob, so the registry is the single source of truth. For each
        # declared path we require exactly one matching creation_rule and that the
        # on-disk file's recipients equal that rule's recipients. We additionally
        # cross-check the filesystem so an orphan file (on disk, not in the
        # registry) is caught too. Fails on:
        #   - a declared path with no on-disk file (declared but never encrypted)
        #   - a declared path matching 0 or >1 creation_rules (ambiguous registry)
        #   - file recipients differing from the rule's expected set (stale hosts)
        #   - an on-disk managed file absent from the registry (orphan)
        do_check() {
          local root
          root="$(repo_root)"
          cd "$root/secrets"
          [ -f .sops.yaml ] || err ".sops.yaml missing; run '${name} rekey'"

          # Registry-declared managed paths (relative to secrets/).
          local declared
          declared="$(cd "$root" && nix eval --json '.#sopsRules' | yq -p json -r '.[].path' | sort -u)"
          [ -n "$declared" ] || { log "No managed paths declared"; return 0; }

          local drift=0 relpath nmatch expected actual
          while IFS= read -r relpath; do
            [ -n "$relpath" ] || continue
            if [ ! -f "$relpath" ]; then
              log "DRIFT: $relpath is declared in the registry but no encrypted file exists (run '${name} edit')"
              drift=1
              continue
            fi

            nmatch="$(rules_matching "$relpath")"
            if [ "$nmatch" -eq 0 ]; then
              log "DRIFT: $relpath matches no creation_rule in .sops.yaml"
              drift=1
              continue
            fi
            if [ "$nmatch" -gt 1 ]; then
              log "DRIFT: $relpath matches $nmatch creation_rules (ambiguous path_regex)"
              drift=1
              continue
            fi

            expected="$(rule_recipients_for "$relpath")"
            actual="$(file_recipients "$relpath")"
            if [ -z "$expected" ]; then
              log "DRIFT: $relpath matching rule has no age recipients"
              drift=1
            elif [ "$actual" != "$expected" ]; then
              log "DRIFT: $relpath recipients do not match its rule (stale host set?)"
              drift=1
            else
              log "OK: $relpath"
            fi
          done <<< "$declared"

          # Orphan guard: any managed file on disk not declared in the registry.
          shopt -s nullglob
          local f relpath
          for f in values/*; do
            relpath="$f"
            if ! grep -qxF "$relpath" <<< "$declared"; then
              log "DRIFT: $relpath exists on disk but is not declared in the registry (orphan)"
              drift=1
            fi
          done

          [ "$drift" -eq 0 ] || err "recipient drift detected; run '${name} rekey'"
        }

        # Create or rotate a raw secret. Plaintext only via \$EDITOR/sops; never printed.
        do_edit() {
          local n="$1" root
          [ -n "$n" ] || err "usage: ${name} edit <name>"
          root="$(repo_root)"
          cd "$root"
          [ -f secrets/.sops.yaml ] || do_rekey
          mkdir -p secrets/values
          ( cd secrets && sops "values/$n" )
          git add "secrets/values/$n"
          log "Edited secrets/values/$n"
        }

        # render <template>: app-side activation for TEXT templates only. Decrypts
        # each ref, substitutes its placeholder, writes a 0600 tmpfs file, prints
        # the path. Caller removes it.
        #
        # CONTRACT (text-only): this renderer is sound for UTF-8/env-style values.
        # It is NOT byte-transparent: command substitution strips trailing
        # newlines from each decrypted value, and bash strings cannot carry NUL.
        # That is fine for dotenv-style refs (KEY=value, no trailing newline
        # significance) but a binary secret must be consumed as a whole file
        # (codgician.secrets.files.<n>.path), never composed through a template.
        # A decrypted value that itself contains a placeholder token is rejected
        # below so later substitutions cannot corrupt or cross-contaminate output.
        do_render() {
          local tpl="$1" root
          [ -n "$tpl" ] || err "usage: ${name} render <template>"
          root="$(repo_root)"
          local content out
          content="$(nix eval --raw ".#renderedTemplates.\"$tpl\".placeholderContent" 2>/dev/null)" \
            || err "no template '$tpl'"
          umask 077
          out="$(mktemp "''${XDG_RUNTIME_DIR:-/dev/shm}/secrets-render.XXXXXX")"
          local ref
          for ref in $(nix eval --json ".#renderedTemplates.\"$tpl\".refs" | yq -p json -r '.[]'); do
            local val placeholder
            placeholder="<SOPS:$ref:PLACEHOLDER>"
            val="$(sops decrypt --input-type binary --output-type binary "$root/secrets/values/$ref")"
            case "$val" in
              *"<SOPS:"*":PLACEHOLDER>"*)
                err "decrypted value of '$ref' contains a placeholder token; refusing to render (would corrupt substitution)" ;;
            esac
            content="''${content//"$placeholder"/$val}"
          done
          printf '%s' "$content" > "$out"
          printf '%s\n' "$out"
        }

        do_for() {
          local root
          root="$(repo_root)"
          shopt -s nullglob
          local f found=0
          for f in "$root"/secrets/values/*; do
            basename "$f"
            found=1
          done
          [ "$found" -eq 1 ] || log "No secrets defined"
        }

        [ $# -ge 1 ] || { show_help; exit 1; }
        cmd="$1"; shift || true
        case "$cmd" in
          -h|--help) show_help; exit 0 ;;
          rekey) do_rekey ;;
          check) do_check ;;
          edit) do_edit "''${1:-}" ;;
          render) do_render "''${1:-}" ;;
          for) do_for ;;
          *) err "Unknown command: $cmd (try --help)" ;;
        esac
      '';
    }
  );
}
