name: evergreen

on:
  schedule:
  - cron: '0 10 * * *'
  workflow_dispatch:

concurrency: evergreen

permissions:
  contents: write
 
jobs:
  evergreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone 
        uses: actions/checkout@v4
        with:
          persist-credentials: 'true'
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update nix flake
        run: nix flake update
      - name: Push changes
        run: |
          if [[ `git status flake.lock --porcelain` ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add flake.lock
            git commit -m "bot: nix flake update"
            git push
          else
            echo "flake.lock is not changed..."
          fi
