creation_rules:
  - path_regex: ^data/all-hosts\.json$
    key_groups:
      - age:
          - age1cpczjrcpde42ejyly34hez3dujj7uh9876l394sghmllcrrne58qwm0fle
          - age1knaylhuawn4g8xduydrph00v32eg6lc8xcd93uu4tm0tw92y0arslqnw5v
          - age1jqt0zj2t4g4gje3vx90dwff5cnm6ttvq05j8hcchxlxhh065xe7skfp9as
          - age13lvf32h446hjz95mcfuzwpe3fwmgexuws8kmmvawhruwlcqch4wqxkxrdp
          - age1c00mjvcpttmqyqgw7qn2tvpz20d4qzjql04h3cmg4ra3l73d2vkqhat6uh
          - age1sv7k78q0t6ezp4rdsqfdsghzt8l0ta7ccjvcs0glay8qhfj2geaqkx7j3p
          - age1hxhsmkyhumkmeqfzrwcru08zm7kynae2q9amqksfju0j3dta64asyqrpkn
          - age1sejtkx2ft6g6mcmk995e9v3e4kq60ywyg4m4hm85hvt9n0ke9ctqrv3lfv
          - age155gspax93arlwep7s6l50hqehcga5ppw7fny3642xzusjdpfd5cs7rtu6r
          - age18s78hg8eyc2nlrug8zscwfqqlwjeyt2827yax0mtht4xhuptcgzsd2lxew
          - age1qxvd2h9zqt2engu6n7kvxzexg3hx53457qdpnv043ftmzrspp5qqh7dj3a
          - age1elg7cj0cntdgwj8z5rk62qlfu9t9shwz7x46d9xpust0dvr3qu3se6twh9
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/all-servers\.json$
    key_groups:
      - age:
          - age1cpczjrcpde42ejyly34hez3dujj7uh9876l394sghmllcrrne58qwm0fle
          - age1c00mjvcpttmqyqgw7qn2tvpz20d4qzjql04h3cmg4ra3l73d2vkqhat6uh
          - age1sv7k78q0t6ezp4rdsqfdsghzt8l0ta7ccjvcs0glay8qhfj2geaqkx7j3p
          - age1hxhsmkyhumkmeqfzrwcru08zm7kynae2q9amqksfju0j3dta64asyqrpkn
          - age1sejtkx2ft6g6mcmk995e9v3e4kq60ywyg4m4hm85hvt9n0ke9ctqrv3lfv
          - age1qxvd2h9zqt2engu6n7kvxzexg3hx53457qdpnv043ftmzrspp5qqh7dj3a
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/fischl-paimon\.json$
    key_groups:
      - age:
          - age1cpczjrcpde42ejyly34hez3dujj7uh9876l394sghmllcrrne58qwm0fle
          - age1hxhsmkyhumkmeqfzrwcru08zm7kynae2q9amqksfju0j3dta64asyqrpkn
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/fischl\.json$
    key_groups:
      - age:
          - age1cpczjrcpde42ejyly34hez3dujj7uh9876l394sghmllcrrne58qwm0fle
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/furina-lumine\.json$
    key_groups:
      - age:
          - age1jqt0zj2t4g4gje3vx90dwff5cnm6ttvq05j8hcchxlxhh065xe7skfp9as
          - age1c00mjvcpttmqyqgw7qn2tvpz20d4qzjql04h3cmg4ra3l73d2vkqhat6uh
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/furina-xianyun\.json$
    key_groups:
      - age:
          - age1jqt0zj2t4g4gje3vx90dwff5cnm6ttvq05j8hcchxlxhh065xe7skfp9as
          - age1qxvd2h9zqt2engu6n7kvxzexg3hx53457qdpnv043ftmzrspp5qqh7dj3a
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/furina\.json$
    key_groups:
      - age:
          - age1jqt0zj2t4g4gje3vx90dwff5cnm6ttvq05j8hcchxlxhh065xe7skfp9as
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/jahoda-paimon\.json$
    key_groups:
      - age:
          - age13lvf32h446hjz95mcfuzwpe3fwmgexuws8kmmvawhruwlcqch4wqxkxrdp
          - age1hxhsmkyhumkmeqfzrwcru08zm7kynae2q9amqksfju0j3dta64asyqrpkn
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/jahoda-public-servers\.json$
    key_groups:
      - age:
          - age13lvf32h446hjz95mcfuzwpe3fwmgexuws8kmmvawhruwlcqch4wqxkxrdp
          - age1c00mjvcpttmqyqgw7qn2tvpz20d4qzjql04h3cmg4ra3l73d2vkqhat6uh
          - age1qxvd2h9zqt2engu6n7kvxzexg3hx53457qdpnv043ftmzrspp5qqh7dj3a
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/jahoda\.json$
    key_groups:
      - age:
          - age13lvf32h446hjz95mcfuzwpe3fwmgexuws8kmmvawhruwlcqch4wqxkxrdp
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/litellm\.json$
    key_groups:
      - age:
          - age1jqt0zj2t4g4gje3vx90dwff5cnm6ttvq05j8hcchxlxhh065xe7skfp9as
          - age1c00mjvcpttmqyqgw7qn2tvpz20d4qzjql04h3cmg4ra3l73d2vkqhat6uh
          - age1hxhsmkyhumkmeqfzrwcru08zm7kynae2q9amqksfju0j3dta64asyqrpkn
          - age18s78hg8eyc2nlrug8zscwfqqlwjeyt2827yax0mtht4xhuptcgzsd2lxew
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/lumine\.json$
    key_groups:
      - age:
          - age1c00mjvcpttmqyqgw7qn2tvpz20d4qzjql04h3cmg4ra3l73d2vkqhat6uh
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/operator\.json$
    key_groups:
      - age:
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/paimon\.json$
    key_groups:
      - age:
          - age1hxhsmkyhumkmeqfzrwcru08zm7kynae2q9amqksfju0j3dta64asyqrpkn
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/public-servers\.json$
    key_groups:
      - age:
          - age1c00mjvcpttmqyqgw7qn2tvpz20d4qzjql04h3cmg4ra3l73d2vkqhat6uh
          - age1qxvd2h9zqt2engu6n7kvxzexg3hx53457qdpnv043ftmzrspp5qqh7dj3a
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/terraform\.json$
    key_groups:
      - age:
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/xianyun\.json$
    key_groups:
      - age:
          - age1qxvd2h9zqt2engu6n7kvxzexg3hx53457qdpnv043ftmzrspp5qqh7dj3a
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
  - path_regex: ^data/zibai\.json$
    key_groups:
      - age:
          - age1elg7cj0cntdgwj8z5rk62qlfu9t9shwz7x46d9xpust0dvr3qu3se6twh9
          - age1hyt4akfl96st0uf4hhkgl2kyd4x4j68ezmqly23zvjvlre4c4vtqat395t
